version: '2'
services:

  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    env_file:
      - .env
    volumes:
      - ${SQL_VOLUME}:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${SQL_PASSWORD}
    networks:
      media:
        ipv4_address: 172.20.0.8

  nextcloud:
    image: nextcloud
    ports:
      - ${NEXTCLOUD_PORT}:80
    links:
      - db
    volumes:
      - ${NEXTCLOUD_VOLUME}:/var/www/html
    depends_on:
      - db
    networks:
      media:
        ipv4_address: 172.20.0.3

  plex:
    image: plexinc/pms-docker
    restart: on-failure
    volumes:
      - ${PLEX_VOLUME_CONFIG}:/config
      - ${PLEX_VOLUME_DATA}:/data
    ports:
      - ${PLEX_PORT}:32400
    network_mode: "host"
    environment:
      - VERSION=latest

  ouroboros:
    container_name: ouroboros
    hostname: ouroboros
    image: pyouroboros/ouroboros
    environment:
      - CLEANUP=true
      - CRON="0 3 * * *"
      - LOG_LEVEL=info
      - SELF_UPDATE=true
      - TZ=America/New_York
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  media:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
